import os
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.output_parsers import StrOutputParser
from prompts import revision_prompt


llm = ChatGoogleGenerativeAI(
    model="gemini-2.0-flash",
    google_api_key=os.getenv("GEMINI_API")
)

parser = StrOutputParser()


chain = revision_prompt | llm | parser

def revise_document(original: str, feedback: str) -> str:
    """
    Uses the LLM chain to revise the original document content based on the feedback.
    
    Args:
        original (str): The original document content.
        feedback (str): The revision feedback or instructions.
    
    Returns:
        str: The revised document content generated by the LLM.
    """
   
    return chain.invoke({
        "original_content": original,
        "feedback": feedback
    })
